platform :ios, '9.0'

target 'movieDB-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movieDB-app

    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'

end
